name: Main workflow
on: [push]
jobs:
  run:
    name: Run
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
        #- windows-latest
    steps:
    - uses: actions/checkout@master
    - uses: tmtk75/gh-act-callee@v1
      with:
        msg: Hello, world!
